api/urls.py
# core django
from django.conf.urls import url, include
from django.http import HttpResponseRedirect
# project
from .views import task, sub_task
from .resources import TaskResource, SubTaskResource

# third party
from tastypie.api import Api
v1_api = Api(api_name='v1')
v1_api.register(TaskResource())
v1_api.register(SubTaskResource())

urlpatterns = [
    url(r'^tasks/$', task, name='task'),
    url(r'^sub-tasks/(?P<id>[0-9]+)/$', sub_task, name='sub-task'),
    url(r'^api/', include(v1_api.urls)),
    url(r'^$', lambda r: HttpResponseRedirect('tasks/')),

]

todolist/urls.py
# core django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('api.urls','api'),namespace='api'))
]

api/models.py
# stdlib
from datetime import timedelta, date

# django core
from django.db import models
from django.core.exceptions import ValidationError
# --------- Models -------------

# This model will provide created, modified fields


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class OldTasksManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter()


class TaskQuerySet(models.QuerySet):
    def old(self):
        print(date.today()-timedelta(days=30))
        return self.filter(is_is_deleted=True, due_date__lte=date.today()-timedelta(days=30))

    def today(self):
        return self.filter(due_date=date.today())

    def this_week(self):
        start_week = self.due_date - timedelta(date.weekday())
        end_week = start_week + timedelta(7)
        return self.filter(due_date__range=[start_week, end_week])

    def next_week(self):
        start_week = self.due_date - timedelta(date.weekday()) + timedelta(7)
        end_week = start_week + timedelta(7)
        return self.filter(due_date__range=[start_week, end_week])

    def over_due(self):
        return self.filter(due_date__gte=date.today())

    def not_trashed(self):
        return self.filter(is_deleted=False)


# class TaskManager(models.Manager):
#     def get_queryset(self):
#         return TaskQuerySet(self.model, using=self._db)

#     def old_tasks(self):
#         return self.get_queryset().old()

#     def today_tasks(self):
#         return self.get_queryset().today_()

#     def this_week_tasks(self):
#         return self.get_queryset().this_week()

#     def next_week_tasks(self):
#         return self.get_queryset().next_week()

#     def overdue_tasks(self):
#         return self.get_queryset().over_due()


class AbstractTask(TimeStampedModel):
    title = models.CharField(
        max_length=50, null=False, blank=False)

    due_date = models.DateField(blank=True, null=True)

    is_task_completed = models.BooleanField(
        default=False)  # completed or pending

    is_deleted = models.BooleanField(default=False)  # soft deleted

    objects = models.Manager()
    manager = TaskQuerySet.as_manager()

    def task_status(self):
        if self.is_task_completed:
            return "completed"
        else:
            return "pending"

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['due_date']
        abstract = True


class Task(AbstractTask):
    title = models.CharField(
        max_length=50, unique=True, null=False, blank=False)

    @property
    def has_sub_tasks(self):
        return self.sub_tasks().count() > 0

    def sub_tasks(self):
        return SubTask.objects.filter(parent_task=self.pk)


class SubTask(AbstractTask):
    parent_task = models.ForeignKey(
        Task, related_name='task', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        if not Task.objects.get(pk=self.parent_task.pk).due_date:
            super(SubTask, self).save(*args, **kwargs)
        elif self.due_date <= Task.objects.get(pk=self.parent_task.pk).due_date:
            super(SubTask, self).save(*args, **kwargs)
        else:
            raise ValidationError(
                'Date must be earlier than or equal to parent task due date')

    class Meta:
        unique_together = ('title', 'parent_task',)

api/views.py
#stdlib
from datetime import date

# core django
from django.shortcuts import render
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
# project
from .models import Task, SubTask
# Create your views here.



# handle task request with pagination
def task(request):

    task_list = Task.manager.not_trashed()
    print(task_list)
    paginator = Paginator(task_list, 10)  # Show 10 tasks per page
    page = request.GET.get('page')
    try:
        tasks = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        tasks = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        tasks = paginator.page(paginator.num_pages)

    return render(request, 'api/task.html', {'page': page, 'Tasks': tasks, 'today_date':date.today()})

# handle sub task request with pagination
def sub_task(request, id):

    sub_task_list = SubTask.manager.not_trashed().filter(parent_task=id)
    paginator = Paginator(sub_task_list, 10)  # Show 10 tasks per page
    page = request.GET.get('page')
    try:
        sub_tasks = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        sub_tasks = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        sub_tasks = paginator.page(paginator.num_pages)

    return render(request, 'api/sub_task.html', {'page': page, 'SubTasks': sub_tasks, 'task': Task.objects.get(pk=id)})

api/templates/api/base.html
<!DOCTYPE HTML>
<html>

<head>
    <title>Todolist</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
        crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
    {% block head %} {% endblock head %}

</head>

<body>
    {% load staticfiles %}
    <div style="position: fixed; width: 100%; height: 100%; z-index: 2;" id="pacman-container" hidden>
        <div style="background-color: black; width: 100%; height: 100%;opacity: 0.5;">

        </div>
        <div style="position: absolute;" id="loader">
            <img src="{% static 'images/pacman.svg' %}" style="position: fixed;z-index: 100;">
        </div>
    </div>
    <div class="container-fluid">
        <div class="row containerImg shadow-sm">
            <div class="col-md-9">
                <form id="search-form">
                    <div class="input-group" style="width: 80%;">
                        <input class="form-control py-2 border-right-0 dark border-grey" type="search" id="search-input" placeholder="search...">
                        <span class="input-group-append">
                            <button class="btn btn-outline-secondary border-left-0 border-grey" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
            </div>

            <div class="col-md-3 h34" style="color:white; padding-top: 16px;">
                <h4 class="text-center">{{ today_date }}</h4>
                <div class="dropdown d-flex justify-content-center">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="date-filter" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        Date Filter
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        <button class="dropdown-item" type="button" id="today">Today</button>
                        <button class="dropdown-item" type="button" id="this-week">This Week</button>
                        <button class="dropdown-item" type="button" id="next-week">Next Week</button>
                        <button class="dropdown-item" type="button" id="over-due">OverDue</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% block body %} {% endblock body %}

</body>

</html>

api/templates/api/pagination.html
<div class="pagination" style="width: 70%;margin: auto;">
    <span class="step-links" style="display: inline-block;">
        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current" style="margin-right: 10px;margin-left: 10px;">
            Page {{page.number }}  of  {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

api/templates/api/sub_task.html
{% extends 'api/base.html' %} {% block head %} {% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/task.css' %}" type="text/css">
<script src="{% static 'js/sub_task.js' %}"></script>

{% endblock head %} {% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 p20">
            <div class="card">
                <div class="card-header" id="home">
                    Home
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item" id="trash">Trash</li>
                </ul>
            </div>
        </div>
        <div class="col-md-9 p20">
            <div class="card">
                <div class="card-header" id="heading">
                    <a href="{% url 'api:task' %}">
                        <i class="fas fa-arrow-left" style="margin-right: 20px;"></i>
                    </a>
                    Sub Tasks [ {{ task.title }} ]
                </div>
            </div>
            <div id="content">
                {% for sub_task in SubTasks %} {% if forloop.counter0|divisibleby:3 %}
                <div class="row shadow-sm">
                    {% endif %}

                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="row">

                                    <div class="col-sm-10">
                                        {% if sub_task.is_task_completed %}


                                        <h5 class="card-title" style="text-decoration: line-through;">{{ sub_task.title }}</h5>
                                        {% else %}
                                        <h5 class="card-title">{{ sub_task.title }}</h5>


                                        {% endif %}
                                    </div>

                                    <div class="col-sm-2 deleteGroup" data-id="{{ sub_task.pk }}">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                    </div>
                                </div>

                                {% if sub_task.is_task_completed %}

                                <p class="card-text" style="text-decoration: line-through;">{{ sub_task.due_date }}</p>

                                {% else %}
                                <p class="card-text">{{ sub_task.due_date }}</p>

                                {% endif %}

                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="round">

                                            {% if sub_task.is_task_completed %}
                                            <input type="checkbox" id="checkbox{{forloop.counter0}}" checked class="checkBoxGroup" /> {% else %}
                                            <input type="checkbox" id="checkbox{{forloop.counter0}}" class="checkBoxGroup" /> {% endif %}

                                            <label for="checkbox{{forloop.counter0}}"></label>
                                        </div>
                                    </div>


                                </div>

                            </div>
                        </div>
                    </div>

                    {% if forloop.counter|divisibleby:3 %}

                </div>

                {% endif %} {% endfor %}

            </div>

        </div>
    </div>
</div>

<div class="col-md-4 offset-4" id="pagination">
    {% include "api/pagination.html" with page=SubTasks %}
</div>

{% endblock body %}

api/templates/api/task.html
{% extends 'api/base.html' %} {% block head %} {% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/task.css' %}" type="text/css">
<script src="{% static 'js/main.js' %}"></script>

{% endblock head %} {% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 p20">
            <div class="card">
                <div class="card-header" id="home">
                    Home
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item" id="trash">Trash</li>
                </ul>
            </div>
        </div>
        <div class="col-md-9 p20">
            <div class="card">
                <div class="card-header" id="heading">
                    Tasks
                </div>
                <ul class="list-group list-group-flush" id="content">

                    {% for task in Tasks %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-sm-1">
                                <div class="round">

                                    {% if task.is_task_completed %}
                                    <input type="checkbox" id="checkbox{{forloop.counter0}}" checked class="checkBoxGroup" /> {% else %}
                                    <input type="checkbox" id="checkbox{{forloop.counter0}}" class="checkBoxGroup" /> {% endif %}

                                    <label for="checkbox{{forloop.counter0}}"></label>
                                </div>
                            </div>

                            {% if task.is_task_completed %}

                            <div class="col-sm-6 pT4" style="text-decoration: line-through;">
                                {% else %}
                                <div class="col-sm-6 pT4">
                                    {% endif %} {% if task.has_sub_tasks %}
                                    <a href="{% url 'api:sub-task' task.pk %}">

                                        {% endif %} {{ task.title }} {% if task.has_sub_tasks %}
                                    </a>
                                    {% endif %}
                                </div>


                                {% if task.is_task_completed %}

                                <div class="col-sm-4" style="text-decoration: line-through">
                                    {% else %}

                                    <div class="col-sm-4">
                                        {% endif %} {% if task.due_date %} {{ task.due_date }} {% endif %}

                                    </div>
                                    <div class="col-sm-1 deleteGroup" data-id="{{ task.pk }}">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                    </div>
                                </div>
                    </li>
                    {% endfor %}

                </ul>


                </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 offset-4" id="pagination">
            {% include "api/pagination.html" with page=Tasks %}
        </div>
        
        {% endblock body %}